Repository 2025-summerbootcamp-TeamG/Frontend, pull requests merged in 2025-07, with the labels that each got.

#15 design: 티켓 더보기 화면 구현
  App/App.tsx
  App/assets/events/backIcon.svg
  App/navigation/AppNavigator.tsx
  App/navigation/HomeStackNavigator.tsx
  App/pages/events/HomeScreen.tsx
  App/pages/events/NewEventsPage.tsx
  App/pages/events/PopularEventsPage.tsx
  App/styles/events/EventCardGrid.tsx
Labels: 🎨 Design

#20 feat: 홈화면 및 더보기 수정
  App/pages/events/HomeScreen.tsx
  App/pages/events/NewEventsPage.tsx
  App/pages/events/PopularEventsPage.tsx
  App/styles/events/EventCardGrid.tsx
Labels: 🎨 Design

#24 하단바 동행자 등록 화면 임시 버튼 삭제
  App/navigation/AppNavigator.tsx
Labels: 🎨 Design

#46 design: 얼굴인식 페이지 연결
  App/navigation/HomeStackNavigator.tsx
  App/pages/events/HomeScreen.tsx
  App/pages/events/PaymentScreen.tsx
  App/pages/tickets/.gitkeep
  App/pages/tickets/CompanionRegisterScreen.tsx
  App/pages/tickets/FaceAuthScreen.tsx
Labels: 🎨 Design

#64 design: 검색결과와 상세정보 연결
  App/components/events/EventCard_home.tsx
  App/components/events/EventCard_search.tsx
  App/navigation/HomeStackNavigator.tsx
  App/pages/events/EventDetailPage.tsx
  App/pages/events/SearchPage.tsx
Labels: 🎨 Design

#71 design: 잔여좌석 + 좌석 번호 배열 맞추기
  App/components/events/SeatMap.tsx
Labels: 🎨 Design

#80 Design: 좌석 최대 예매갯수 설정
  App/assets/events/EventsMock.tsx
  App/components/events/SeatMap.tsx
  App/pages/events/SeatSelectPage.tsx
Labels: 🎨 Design

#85 design: 좌석 가격과 결제창 연결
  App/assets/events/EventsMock.tsx
  App/components/events/SeatMap.tsx
  App/pages/events/PaymentScreen.tsx
  App/pages/events/SeatSelectPage.tsx
Labels: 🎨 Design

#87 design: 홈화면 비대칭 수정
  App/styles/events/EventCardGrid.tsx
Labels: 🎨 Design

#92 Chore: api연동 파일 수정
  App/services/.gitkeep
  App/services/EventService.ts
  App/services/TicketService.ts
  App/services/Types.ts
  App/services/UserService.ts
  App/services/apiClient.ts
Labels: 🧭 Chore

#106 feat: 인기티켓 정렬 수정
  App/.env
  App/pages/events/NewEventsPage.tsx
  App/pages/events/PopularEventsPage.tsx
  App/services/apiClient.ts
Labels: 🚀 Feat

#111 feat: 행사 상세 정보 조회 페이지 + 예매하기 버튼 토큰 여부
  .gitignore
  App/env.example
  App/pages/events/EventDetailPage.tsx
  App/pages/events/SearchPage.tsx
  App/pages/events/SeatSelectPage.tsx
  App/pages/user/.gitkeep
  App/services/EventService.ts
  App/services/TicketService.ts
Labels: 🚀 Feat

#119 feat: 존별 좌석 정보 api 연동..(잔여좌석 수정필요)
  App/components/events/SeatMap.tsx
  App/navigation/HomeStackNavigator.tsx
  App/pages/events/EventDetailPage.tsx
  App/pages/events/SeatSelectPage.tsx
  App/services/EventService.ts
  App/services/Types.ts
  App/services/apiClient.ts
Labels: 🚀 Feat

#139 feat: 존 별 좌석, 예매하기 수정!!!!!
  App/pages/events/PaymentScreen.tsx
  App/pages/events/SeatSelectPage.tsx
  App/services/EventService.ts
Labels: 🚀 Feat
